### ISSUE TITLE
Moderna_server encountered a problem -> moderna/PdbConverter.py

### ISSUE THREAD

**Issue by Liriela** [lenarother/moderna#61]
Problem occured in 144077733467_frag

The problem is:
Traceback (most recent call last):
  File "/home/webadmin/django_dbs/moderna_server/moderna_launcher.py", line 549, in main_production
    launch.run_moderna()
  File "/home/webadmin/django_dbs/moderna_server/moderna_launcher.py", line 247, in run_moderna
    self.convert_format()
  File "/home/webadmin/django_dbs/moderna_server/moderna_launcher.py", line 542, in convert_format
    conv.convert_structure()
  File "/usr/local/lib/python2.6/dist-packages/moderna/PdbConverter.py", line 250, in convert_structure
    converted_resi = self.convert_resi_list(resi_list)
  File "/usr/local/lib/python2.6/dist-packages/moderna/PdbConverter.py", line 204, in convert_resi_list
    new_resi_list.append(self.convert_resi(resi))
  File "/usr/local/lib/python2.6/dist-packages/moderna/PdbConverter.py", line 192, in convert_resi
    atom_list = self.get_new_at_list(resi)
  File "/usr/local/lib/python2.6/dist-packages/moderna/PdbConverter.py", line 181, in get_new_at_list
    else: new_at_list.append(self.change_at_name(at, at.id))
  File "/usr/local/lib/python2.6/dist-packages/moderna/PdbConverter.py, line 77, in change_at_name
    element = new_name.strip()[0]
IndexError: string index out of range

**Comment by lenarother** [comment]
Hi @Liriela,

The input file is not correct.
The PDB format specification (ftp://ftp.wwpdb.org/pub/pdb/doc/format_descriptions/Format_v33_A4.pdf, page 180) says:

```
77 -78        LString(2)   element       Element symbol, right-justified
```

In the file that causes error the element is on the position 75.
