### ISSUE TITLE
Moderna server encountered a problem -> Bio/PDB/PDBParser.py

### ISSUE THREAD

**Issue by Liriela** [lenarother/moderna#62]
Problem occured in 144099280745_abc

The problem is:
Traceback (most recent call last):
  File "/home/webadmin/django_dbs/moderna_server/moderna_launcher.py", line 549, in main_production
    launch.run_moderna()
  File "/home/webadmin/django_dbs/moderna_server/moderna_launcher.py", line 247, in run_moderna
    self.convert_format()
  File "/home/webadmin/django_dbs/moderna_server/moderna_launcher.py", line 540, in convert_format
    st = PDBParser().get_structure('', self.template)
  File "/usr/local/lib/python2.6/dist-packages/Bio/PDB/PDBParser.py", line 79, in get_structure
    self._parse(file.readlines())
  File "/usr/local/lib/python2.6/dist-packages/Bio/PDB/PDBParser.py", line 106, in _parse
    self.trailer=self._parse_coordinates(coords_trailer)
  File "/usr/local/lib/python2.6/dist-packages/Bio/PDB/PDBParser.py", line 164, in _parse_coordinates
    resseq=int(line[22:26].split()[0])   # sequence identifier
ValueError: invalid literal for int() with base 10: 'A'

**Comment by lenarother** [comment]
Hi @Liriela, 

The input file is not correct.
The [PDB format specification](ftp://ftp.wwpdb.org/pub/pdb/doc/format_descriptions/Format_v33_A4.pdf), (page 180) says:
22             Character     chainID      Chain identifier.
23 -26        Integer       resSeq       Residue sequence number.

In the file that causes error chain identifier is on position 23.
That's why the PDBParser complains:
resseq=int(line[22:26].split()[0]) # sequence identifier
ValueError: invalid literal for int() with base 10: 'A'
